USE [master]
GO

CREATE DATABASE [pharmacy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'pharmacy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pharmacy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'pharmacy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\pharmacy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [pharmacy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [pharmacy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [pharmacy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [pharmacy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [pharmacy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [pharmacy] SET ARITHABORT OFF 
GO

ALTER DATABASE [pharmacy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [pharmacy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [pharmacy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [pharmacy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [pharmacy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [pharmacy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [pharmacy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [pharmacy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [pharmacy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [pharmacy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [pharmacy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [pharmacy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [pharmacy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [pharmacy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [pharmacy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [pharmacy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [pharmacy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [pharmacy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [pharmacy] SET  MULTI_USER 
GO

ALTER DATABASE [pharmacy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [pharmacy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [pharmacy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [pharmacy] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [pharmacy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [pharmacy] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [pharmacy] SET QUERY_STORE = OFF
GO

ALTER DATABASE [pharmacy] SET  READ_WRITE 
GO


USE [pharmacy]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Goods](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Goods] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pharmacies](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](50) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Pharmacies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Warehouses](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PharmacyId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Warehouses] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Batchs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GoodId] [int] NOT NULL,
	[WarehouseId] [int] NOT NULL,
	[Quantity] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Batchs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

